# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TourGuide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TourGuide

pod 'FirebaseCore'

  target 'TourGuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TourGuideUITests' do
    # Pods for testing
  end

end
